### ISSUE TITLE
Doesn't work in Word 2016

### ISSUE THREAD

**Issue by et2010** [oleksiykovtun/Word-Export-to-PDF#2]
When I click the `Save PDF here`, it just opens the file with Word 2016, no PDF exported.

Besides, how could I uninstall it?

**Comment by alex-vt** [comment]
Sorry I don't have that version to check. I added a new file `ExportToPDF-remove.reg` to run to remove the context menu item, and Microsoft Visual Basic for Applications (Alt + F11 in Word) should allow removing `ExportToPDF.bas`. Did that work? If not, try restarting your computer.

**Comment by et2010** [comment]
Thanks for the guide. I removed the extension without restarting. Thanks!
